# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 23:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('start_date', models.DateField()),
                ('num_months_between_occ', models.IntegerField()),
                ('day_of_month_of_occ', models.IntegerField()),
                ('num_days_offset', models.IntegerField()),
            ],
        ),
    ]
