# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 01:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('true_app', '0002_auto_20170325_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='calculated_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
